/* tslint:disable */
/* eslint-disable */
/**
 * NIS 2 Cybersecurity Audit Platform API
 * API Gateway pour la plateforme SaaS d\'audit de cybersécurité. Cette API orchestre les microservices d\'audit (M365, Google), de normalisation et de remédiation.  **Architecture :** - Authentification : Bearer Token (JWT via Clerk/NextAuth) - Format de réponse : JSON (Standardisé) - Standards : SARIF (Audit Results), OCSF (Logs) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@audit-tool.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Nis2ScoreResponseBreakdown {
    /**
     * Score Art. 21.2(i) - Contrôle d\'accès
     */
    'accessControl'?: number;
    /**
     * Score Art. 21.2(b) - Gestion incidents
     */
    'incidentResponse'?: number;
    /**
     * Score Art. 21.2(d) - Sécurité chaîne d\'approvisionnement
     */
    'supplyChain'?: number;
}

