/* tslint:disable */
/* eslint-disable */
/**
 * NIS 2 Cybersecurity Audit Platform API
 * API Gateway pour la plateforme SaaS d\'audit de cybersécurité. Cette API orchestre les microservices d\'audit (M365, Google), de normalisation et de remédiation.  **Architecture :** - Authentification : Bearer Token (JWT via Clerk/NextAuth) - Format de réponse : JSON (Standardisé) - Standards : SARIF (Audit Results), OCSF (Logs) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@audit-tool.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface RemediationRequest {
    /**
     * ID unique de la vulnérabilité (issu du rapport SARIF)
     */
    'findingId': string;
    'action': RemediationRequestActionEnum;
    /**
     * Paramètres optionnels pour le correctif (ex: liste d\'utilisateurs exclus)
     */
    'parameters'?: object;
}

export const RemediationRequestActionEnum = {
    EnableMfa: 'ENABLE_MFA',
    DisableGuest: 'DISABLE_GUEST',
    EnforceLogs: 'ENFORCE_LOGS'
} as const;

export type RemediationRequestActionEnum = typeof RemediationRequestActionEnum[keyof typeof RemediationRequestActionEnum];


