/* tslint:disable */
/* eslint-disable */
/**
 * NIS 2 Cybersecurity Audit Platform API
 * API Gateway pour la plateforme SaaS d\'audit de cybersécurité. Cette API orchestre les microservices d\'audit (M365, Google), de normalisation et de remédiation.  **Architecture :** - Authentification : Bearer Token (JWT via Clerk/NextAuth) - Format de réponse : JSON (Standardisé) - Standards : SARIF (Audit Results), OCSF (Logs) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@audit-tool.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SarifReportRunsInner } from './sarif-report-runs-inner';

/**
 * Structure simplifiée d\'un rapport SARIF pour le frontend
 */
export interface SarifReport {
    'runs'?: Array<SarifReportRunsInner>;
}

