/* tslint:disable */
/* eslint-disable */
/**
 * NIS 2 Cybersecurity Audit Platform API
 * API Gateway pour la plateforme SaaS d\'audit de cybersécurité. Cette API orchestre les microservices d\'audit (M365, Google), de normalisation et de remédiation.  **Architecture :** - Authentification : Bearer Token (JWT via Clerk/NextAuth) - Format de réponse : JSON (Standardisé) - Standards : SARIF (Audit Results), OCSF (Logs) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@audit-tool.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface StartAuditRequest {
    /**
     * ID interne du client (Organisation)
     */
    'tenantId'?: string;
    /**
     * Les environnements à scanner.
     */
    'targets': Array<StartAuditRequestTargetsEnum>;
    'scanType'?: StartAuditRequestScanTypeEnum;
}

export const StartAuditRequestTargetsEnum = {
    M365: 'M365',
    GoogleWorkspace: 'GOOGLE_WORKSPACE',
    Aws: 'AWS'
} as const;

export type StartAuditRequestTargetsEnum = typeof StartAuditRequestTargetsEnum[keyof typeof StartAuditRequestTargetsEnum];
export const StartAuditRequestScanTypeEnum = {
    Quick: 'QUICK',
    Full: 'FULL',
    Deep: 'DEEP'
} as const;

export type StartAuditRequestScanTypeEnum = typeof StartAuditRequestScanTypeEnum[keyof typeof StartAuditRequestScanTypeEnum];


