FROM node:20-slim AS builder
WORKDIR /app
RUN apt-get update && apt-get install -y openssl
COPY package*.json ./
RUN npm install
COPY . .
RUN npx prisma generate --schema=libs/db/schema.prisma

# On garde une image de runtime propre
FROM node:20-slim
WORKDIR /app
RUN apt-get update && apt-get install -y openssl libpq-dev
COPY --from=builder /app /app
CMD ["npx", "tsx", "scripts/sync-github.ts"]