/* tslint:disable */
/* eslint-disable */
/**
 * NIS 2 Cybersecurity Audit Platform API
 * API Gateway pour la plateforme SaaS d\'audit de cybersécurité. Cette API orchestre les microservices d\'audit (M365, Google), de normalisation et de remédiation.  **Architecture :** - Authentification : Bearer Token (JWT via Clerk/NextAuth) - Format de réponse : JSON (Standardisé) - Standards : SARIF (Audit Results), OCSF (Logs) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@audit-tool.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { RemediationRequest } from '../models';
/**
 * RemediationApi - axios parameter creator
 */
export const RemediationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Lance une action corrective sur le tenant cible (ex: Activer MFA). Cette action est critique et sera logguée dans l\'audit trail (OCSF).
         * @summary Appliquer un correctif de sécurité
         * @param {RemediationRequest} remediationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        executeRemediation: async (remediationRequest: RemediationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'remediationRequest' is not null or undefined
            assertParamExists('executeRemediation', 'remediationRequest', remediationRequest)
            const localVarPath = `/remediations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(remediationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RemediationApi - functional programming interface
 */
export const RemediationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RemediationApiAxiosParamCreator(configuration)
    return {
        /**
         * Lance une action corrective sur le tenant cible (ex: Activer MFA). Cette action est critique et sera logguée dans l\'audit trail (OCSF).
         * @summary Appliquer un correctif de sécurité
         * @param {RemediationRequest} remediationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async executeRemediation(remediationRequest: RemediationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.executeRemediation(remediationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RemediationApi.executeRemediation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RemediationApi - factory interface
 */
export const RemediationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RemediationApiFp(configuration)
    return {
        /**
         * Lance une action corrective sur le tenant cible (ex: Activer MFA). Cette action est critique et sera logguée dans l\'audit trail (OCSF).
         * @summary Appliquer un correctif de sécurité
         * @param {RemediationRequest} remediationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        executeRemediation(remediationRequest: RemediationRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.executeRemediation(remediationRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RemediationApi - object-oriented interface
 */
export class RemediationApi extends BaseAPI {
    /**
     * Lance une action corrective sur le tenant cible (ex: Activer MFA). Cette action est critique et sera logguée dans l\'audit trail (OCSF).
     * @summary Appliquer un correctif de sécurité
     * @param {RemediationRequest} remediationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public executeRemediation(remediationRequest: RemediationRequest, options?: RawAxiosRequestConfig) {
        return RemediationApiFp(this.configuration).executeRemediation(remediationRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

